### PR TITLE
WIP V3 updates

### PR DESCRIPTION
**Pull request by DougBurke**
# Note

I am breaking this up into smaller PRs, so the following is out of date (in that it talks about features that have already been merged).

# Details

Adding symbols based on a manual review of Elm VegaLite module 1.12.0 and the vega-lite 3.3.0 schema. The idea is to add missing functionality that may not have been in the original version, or that is now enabled by the use of the v3 VegaLite schema.

Documentation has also been expanded.

Not sure when I'll get bored doing this (i.e. how many of the changes from the Elm version I'll take), but I wanted to warn people that things are in flux. Please holler if you see something wrong or there's something you need.

I I'd thought about this, I could have done a release where symbols were deprecated, and providing aliases for changed functionality, but I think that is unlikely to happen now (and this is still a new module so breaking the API is slightly-more defensible ...).

## Breaking changes

- `SReverse` was removed from `ScaleProperty` as `PSort` is used to define the ordering
- `ScSequential` was removed from `Scale` as `ScLinear` should be used
- `AxTitleMaxLength` was removed from `AxisProperty` and `TitleMaxLength` from `AxisConfig`
  as `AxTitleLimit` (new in this release) and `TitleLimit` should be used
- `StackProperty` was renamed to `StackOffset` and a new type `StackProperty` was added
- `LegendConfig`: removed the constructors `EntryPadding`, `GradientHeight`, `GradientLabelBaseline`, and `GradientWidth`; renamed the remaining constructors so that they all start with `Le` - so for example renamed `Orient` to `LeOrient` (`Orient` is now an `AxisConfig` constructor).
- `Average` was removed from `Operation` as `Mean` should be used
- `LEntryPadding` was removed from `LegendProperty`
- The `MDataCondition`, `TDataCondition`, and `HDataCondition` constructors - from `MarkChannel`, `TextChannel`, and `HyperlinkChannel` respectively - now accept a list of tests
- the `MarkOrientation` type has been renamed `Orientation`
- the constructors for the `ViewConfig` type now all start with `View`
- the `Divide` constructor of `BinProperty` now takes a list of `Double` rather than two of them

### Changes within the 0.4 development

- `MBorders`, added in #10, and new to this release, has been changed from taking a boolean to a list of `MarkProperty`

## New Types

- `BoolOrNumber` which is a horrible hack I came up with and may not survive contact with reality
- `VLProperty` has added constructors: these are not exposed directly to the user
- `Format`: added `DSV`
- `CompositionAlignment`
- `PointMarker`
- `ImputeProperty` and `ImMethod`
- `GraticuleProperty`
- `StackProperty` and `StackOffset` (this is a breaking change since the old StackProperty has been
  renamed to StackOffset and new constructor added)
- `Window`, `WOperation`, `WindowProperty`
- `FacetConfig`
- `SortField`, `StrokeCap`, `StrokeJoin`
- `ViewBackground`
- `TooltipContent`
- `LineMarker`
- `Bounds`
- `LegendLayout` and `BaseLegendLayout`

### New constructors

- `Channel`: added `ChLongitude`, `ChLatitude`, `ChLongitude2`, `ChLatitude2`, `ChStrokeWidth`, `ChStrokeOpacity`, `ChText`, `ChTooltip`, `ChHref`, `ChKey`
- `MarkChannel`: added `MBinned`, `MImpute`, `MSort`, `MTitle`, `MNoTitle`
- `MarkProperty`: added `MBox`, `MHRef`, `MLine`, `MOrder`, `MPoint`, `MRule`, `MStrokeCap`, `MStrokeJoin`, `MTicks`, `MMedian`, `MOutliers`, `MStrokeMiterLimit`, `MTooltip`, `MX`, `MY`, `MX2`, `MY2`, `MXOffset`, `MYOffset`, `MX2Offset`, `MY2Offset`
- `Arrangement`: added `Flow` 
- `SortProperty`: added `CustomSort`, `ByRepeatOp`, `ByFIeldOp`, `ByChannel`
- `PositionChannel`: added `PHeight`, `PWidth`, `PNumber`, `PBinned`, `PTitle`, `PNoTitle`, `PImpute`
- `AxisProperty`: added `AxBandPosition`, `AxDomainColor`, `AxDomainDash`, `AxDomainDashOffset`, `AxDomainOpacity`, `AxDomainWidth`, `AxFormatAsNum`, `AxFormatAsTemporal`, `AxGridColor`, `AxGridDash`, `AxGridDashOffset`, `AxGridOpacity`, `AxGridWidth`, `AxLabelAlign`, `AxLabelBaseLine`, `AxLabelBound`, `AxLabelColor`, `AxLabelFlush`, `AxLabelFlushOffset`, `AxLabelFont`, `AxLabelFontSize`, `AxLabelFontStyle`, `AxLabelFontWidth`, `AxLabelLimit`, `AxLabelOpacity`, `AxLabelSeparation`, `AxTickColor`, `AxTickDash`, `AxTickDashOffset`, `AxTickExtra`, `AxTickMinStep`, `AxTickOffset`, `AxTickOpacity`, `AxTickRound`, `AxTickWidth`, `AxNoTitle`, `AxTitleAnchor`, `AxTitleBaseline`, `AxTitleColor`, `AxTitleFont`, `AxTitleFontSize`, `AxTitleFontStyle`, `AxTitleFontWeight`, `AxTitleLimit`, `AxTitleOpacity`, `AxTitleX`, `AxTitleY`
- `LegendConfig`: added **many** new constructors
- `LegendProperty`: added `LClipHeight`, `LColumnPadding`, `LColumns`, `LCornerRadius`, `LDirection`, `LFormatAsNum`, `LFormatAsTemporal`, `LGradient*`, `LFillColor`, `LGridAlign`, `LLabel*`, `LRowPadding`, `LStrokeColor`, `LSymbol*`, `LTickMinStep`, `LNoTitle`, `LTitle*`, `LeX`, `LeY`
- `Projection`: added `Identity`
- `ProjectionProperty`: added `PrScale`, `PrTranslate`, `PReflectX`, `PReflectY`
- `ConfigurationProperty`: added `GeoshapeStyle`, `FacetStyle`, `HeaderStyle`, `NamedStyles`, `TrailStyle`
- `AxisConfig`: added `DomainDash`, `DomainDashOffset`, `DomainOpacity`, `GridDashOffset`, `LabelAlign`, `LabelBaseline`, `LabelBound`, `LabelFlush`, `LabelFlushOffset`, `LabelFontStyle`, `LabelFontWeight`, `LabelOpacity`, `LabelSeparation`, `Orient`, `TickDashOffset`, `TickExtra`, `TickOffset`, `TickOpacity`, `TitleAnchor`, `TitleFontStyle`, `TitleOpacity`
- `HeaderProperty`: added `HFormatAsNum`, `HFormatAsTemporal`, `HLabelAlign`, `HLabelAnchor`, `HLabelAngle`, `HLabelColor`, `HLabelFont`, `HLabelFontSize`, `HLabelLimit`, `HLabelOrient`, `HLabelPadding`, `HTitleAlign`, `HTitleAnchor`, `HTitleAngle` `HTitleBaseline`, `HTitleColor`, `HTitleFont`, `HTitleFontSize`, `HTitleFontWeight`, `HTitleLimit`, `HTitleOrient`, `HTitlePadding`, `HNoTitle`
- `FacetChannel`: added `FSort`, `FTitle`, `FNoTitle`
- `DetailChannel`: added `DImpute`
- `Mark`: added `Boxplot` and `Trail`
- `Filter`: added `FLessThan`, `FLessThanEq`, `FGreaterThan`, `FGreaterThanEq`, `FValid`
- `TextChannel`: added `TBinned`, `TFormatAsNum`, `TFormatAsTemporal`, `TTitle`, `TNoTItle`
- `HyperlinkChannel`: added `HBinned`
- `ScaleConfig`: added `Sc[Bar|Rect]BandPadding[Inner|Outer]`
- `Scale`: added `ScSymLog`, `ScQuantile`, `ScQuantize`
- `ScaleProperty`: added `SExponent`, `SConstant`, `SBins`, and `SBase`
- `SelectionProperty`: added `Clear` and `SInit`
- `LegendOrientation`: added `LOTop` and `LOBottom`
- `ViewConfig`: added `ViewCornerRadius`, `ViewOpacity`, `ViewStrokeMiterLimit`, `ViewStrokeCap`, `ViewStrokeJoin`

## New functions

- `dataName`, `dataSequence`, `dataSequenceAs`
- `sphere`, `graticule`
- `impute`
- `joinAggregate`
- `stack`
- `flatten`, `flattenAs`, `fold`, `foldAs`
- `window`
- `sample`
- `vlConcat`, `columns`, `align`, `alignRC`, `spacing`, `spacingRC`, `center`, `centerRC`
- `facetFlow`, `repeatFlow`
- `viewBackground`
- `fillOpacity`, `strokeOpacity`, `strokeWidth`
- `bounds`

## Other changes

Added an `Opacity` type synonymn (for `Double`) for documentation purposes. Would it make sense to make this a separate type - so the 0-to-1 range could be enforced - or would this just get in the way too much?

The `datasets` command hopefully now works (fixing #20), but has seen limited testing.

The `SScheme` constructor for `ScaleProperty` now accepts 1, 2, or 3 optional arguments, that map to `"count`", "`extent`", and "`count` followed by `extent`".

### CODE REVIEW

**Comment by BinderDavid** [comment]
This looks great! This weekend I'll compare this with our use and give feedback if we're still missing functionality after these changes.

**Comment by adamConnerSax** [comment]
Cool!  Having more stuff in there is great!

**Comment by DougBurke** [comment]
There are definitely parts of this that haven't been properly tested (e.g. I am currently seeing something odd with `dataSequenceAs`)

**Comment by DougBurke** [comment]
@adamConnerSax I've just committed 3113e9d which changes your `MBorders Bool` - from #10 - to `MBorders [MarkProperty]`. The schema accepts both, but I can't find documentation on what a bool means in this case, so I've currently followed the same scheme as the other constructors.

If useful, we would want to work out how to support passing a bool, but hopefully the current set up doesn't break your work visualizations.

**Comment by adamConnerSax** [comment]
Thanks for the heads up! I’ll adjust any thing necessary on my end. 
And thanks for adding all the new stuff! I find hvega super useful and the more that’s in there, the better!

**Comment by DougBurke** [comment]
About to rebase to integrate test support and clean up some of the history.

**Comment by DougBurke** [comment]
I haven't merged the "BoolOrNumber" change as I don't like the type, and want to think about it a bit.

**Comment by DougBurke** [comment]
I am closing this as I have taken all I want to from this: I decided against using the ungainly `BoolOrNumber` approach I explored in 57ca81e

**Pull request closed without merging**
