### PR TITLE
Ergonomics improvements

### PR DESCRIPTION
**Pull request by ocramz**
* Bumped version to 0.2 due to API change (renamed Left and Right to LOLeft and LORight)

* Small documentation fixes

### CODE REVIEW

**Comment by DougBurke** [comment]
@ocramz thanks for the updates.

@adamConnerSax - from what you said in #8 I don't think this PR should conflict with your work, but wanted to check before merging.

**Comment by ocramz** [comment]
Hi again, I just realized we don't need the ToJSON instance for VegaLite because its contents are already an `aeson` Value. I've added some detail in the example to clarify this.

**Comment by adamConnerSax** [comment]
Won't conflict at all.  I'm just adding some constructors to a couple of types.  Thanks for checking!

**Comment by DougBurke** [comment]
@ocramz no problems.

**Comment by DougBurke** [comment]
@ocramz - do you think you've finished with this now? I have a small addition (to update the associated notebook for this change) and don't want to add it to this PR until I know I'm not going to mess up your work.

**Comment by ocramz** [comment]
@DougBurke yes, this is done for now, thank you! 👍

**Pull request merged**
