### PR TITLE
Added script names and exported

### PR DESCRIPTION
**Pull request by adamConnerSax**
This is all I had in mind.  Just gives a user access to the names you think match so that if those change in a new version, anyone who is creating their own docs (like me!) and embedding can choose to stay in sync with whatever version you think best.

### CODE REVIEW

**Comment by adamConnerSax** [comment]
And sorry.  It made all the whitespace changes again.  I don't know how not to!  It does brittany on save!
Anyway, if you want to go ahead  with it, I can figure out how to fix or you can just copy/paste and skip the PR.

**Comment by DougBurke** [comment]
Questions I have are

 - is this a sufficient set of Javascript libraries
 - how stable is this set (i.e. I am concerned about baking in choices that may quickly become outdated)?

I initially came up - in `ihaskell-vega` - with a set of javascript modules by looking at vega-embed and then randomly trying things until I got output in a IHaskell notebook. I have no experience with other backends.

It'd be great if other users can comment - I know @ocramz has interest with `lucid-extras`, and maybe @BinderDavid or @mpickering for https://github.com/mpickering/eventlog2html

**Comment by DougBurke** [comment]
ps thanks for creating this from the discussion in #10

**Comment by BinderDavid** [comment]
First of all, thanks for the great library @DougBurke. You can get a good idea about how we use hvega by taking a glance at the following two files:

https://github.com/mpickering/eventlog2html/blob/master/src/Eventlog/HtmlTemplate.hs
https://github.com/mpickering/eventlog2html/blob/master/src/Eventlog/VegaTemplate.hs

The workflow of eventlog2html is that you convert foo.eventlog files to interactive foo.html files, which you can inspect on your local computer or share with colleagues. Since users should be able to use these files while working offline, the javascript libraries (vega, vegalite and vega-embed) are by default baked into the html file (although there is an option to use a CDN if you want smaller files).
At the moment we do this by having a copy of the JS libraries in the repository, which we include with file-embed.

If you search for "injectJson, toJson, object" in VegaTemplate.hs you find the places where features are still missing from hvega, and where we had to include the Json by hand. I have planned to look at these places more closely and see if I can write some PRs for features that we miss. I'll hopefully have soon time to do that.

I couldn't take a closer look at this PR right now, but maybe I'll have time tomorrow. Also, Ihave never used IHaskell, so I can't comment on that.

**Comment by mpickering** [comment]
I don't know what this PR does, there are too many irrelevant formatting changes to see what has changed.

**Comment by adamConnerSax** [comment]
Sorry! 
The only changes are adding
```
vegaScriptName :: T.Text
vegaScriptName = "vega@5"

vegaLiteScriptName :: T.Text
vegaLiteScriptName = "vega-lite@3"

vegaEmbedScriptName :: T.Text
vegaEmbedScriptName = "vega-embed@4"

vlEmbedScriptNames :: [T.Text]
vlEmbedScriptNames = [vegaScriptName, vegaLiteScriptName, vegaEmbedScriptName]```
```
and then those being used here:
```
toHtml :: VegaLite -> TL.Text
toHtml vl = TL.unlines
  [ "<!DOCTYPE html>"
  , "<html>"
  , "<head>"
  , "  <!-- Import Vega 5 & Vega-Lite 3 (does not have to be from CDN) -->"
  , "  <script src=\"https://cdn.jsdelivr.net/npm/"
  <> TL.fromStrict vegaScriptName
  <> "\"></script>"
  , "  <script src=\"https://cdn.jsdelivr.net/npm/"
  <> TL.fromStrict vegaLiteScriptName
  <> "\"></script>"
  , "  <!-- Import vega-embed -->"
  , "  <script src=\"https://cdn.jsdelivr.net/npm/"
  <> TL.fromStrict vegaEmbedScriptName
  <> "\"></script>"
  , "</head>"
  , "<body>"
  , "<div id=\"vis\"></div>"
  , "<script type=\"text/javascript\">"
  , ("  var spec = " <> (A.encodeToLazyText $ fromVL vl) <> ";")
  , "  vegaEmbed(\'#vis\', spec).then(function(result) {"
  , "  // Access the Vega view instance (https://vega.github.io/vega/docs/api/view/) as result.view"
  , "  }).catch(console.error);"
  , "</script>"
  , "</body>"
  , "</html>"
  ]
```
and they are also exported so they can be used by library users.

**Comment by adamConnerSax** [comment]
Okay.  I think this latest committed version has the whitespace issue fixed.  Maybe that'll be easier to look at.

**Pull request closed without merging**
